# $ docker-compose up -d
# $ docker-compose exec postgres psql -U root postgres

version: "3.7"
services:
  postgres-latest:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root
    - POSTGRES_DB=postgres
  restart: always
