    # RabbitMQ, used by the flask app to queue up jobs whee
    rabbit:
        hostname: rabbit
        image: rabbitmq:3-management
        restart: "always" 
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
            - RABBITMQ_DEFAULT_VHOST=rabbit
        ports:
            - "15672:15672"
            - "5672:5672"
            - "5671:5671"
        volumes:
          - "/data:/var/lib/rabbitmq"
