version: "3.7"

services:
  mongo-latest:
    container_name: mongo-latest
    image: mongo:latest
    network_mode: "bridge"
    command: --auth
    volumes:
      - type: volume
        source: mongo-latest__data
        target: /data/db
        volume:
          nocopy: false
      - type: volume
        source: mongo-latest__config
        target: /data/configdb
        volume:
          nocopy: false
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"


volumes:
  mongo-latest__data:
    driver: local
  mongo-latest__config:
    driver: local