version: "3"

volumes:
  mariadb:
    driver: local

networks:
    db:
        driver: bridge

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER:  devel 
      MYSQL_PASSWORD: devel
    expose:
      - "40000"
    ports:
      - "40000:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      db:

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    expose:
      - "40001"
    ports:
      - "40001:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306 
      - UPLOAD_LIMIT=385265204
      - MAX_EXECUTION_TIME=6000
      - MEMORY_LIMIT=1024M
    networks:
      db:
