services:
  web:
    build: .
    ports:
      - "3000:3000"
    healthcheck:
      test: curl -f http://localhost:3000/health || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s